### ISSUE TITLE
cardStateChanged event doesn't have Directions

### ISSUE THREAD

**Issue by jullicer** [thesayyn/ngx-swing#1]
It would be useful to know which direction the card was thrown out

**Comment by thesayyn** [comment]
Willing to take a look at it :). Also I appreciate a pr if you willing to help

**Comment by jullicer** [comment]
@thesayyn what do you mean by pr ? 

also on offsetStateChanged and if possible can we pass the element ?

**Comment by thesayyn** [comment]
I mean pull request by saying pr.

So yes it is possible and I will take look tomorrow

**Comment by thesayyn** [comment]
Hello  again @jullicer 

In the demo code, I'm subscribing to card events right from their dom elements.

Like so
```
<div swingStack>
  <div
    *ngFor="let image of ['angular.svg', 'ionic.svg', 'capacitor.png']" 
    swingCard 
    (cardStateChange)="cardStateChanged($event)"
    (offsetStateChange)="offsetStateChanged($event)">
    <img [src]="'../assets/images/'+ image">
  </div>
</div>
```
Since you know that which card you are dealing with, it doesn't sends it's own reference through events. However, you can get card references if you subscribe to events from swingStack like so
```
<div 
  swingStack
  (cardStateChange)="cardStateChanged($event)"
  (offsetStateChange)="offsetStateChanged($event)">
  <div *ngFor="let image of ['angular.svg', 'ionic.svg', 'capacitor.png']"   swingCard>
    <img [src]="'../assets/images/'+ image">
  </div>
</div>
```

**Comment by thesayyn** [comment]
Closing this as resolved
